packages:
    - packages/*
    - apps/*

catalog:
    '@types/node': ^24.10.1
    tsx: ^4.7.0
    typescript: ^5.9.3

onlyBuiltDependencies:
    - esbuild
    - onnxruntime-node
    - protobufjs
    - sharp
